#include "Error.h"
#include "Formatter.h"
#include "StringBuffer.h"

#ifndef __linux__
#    include <string.h>
#endif

namespace Ty {

namespace {

#if __linux__
enum class Errno : u32 {
    NoError = 0,
    Permission = 1,
    NoEntry = 2,
    Search = 3,
    Interrupted = 4,
    IO = 5,
    NoIO = 6,
    TooBig = 7,
    NoExec = 8,
    BadFile = 9,
    Child = 10,
    Again = 11,
    NoMemory = 12,
    Access = 13,
    Fault = 14,
    NotBlock = 15,
    Busy = 16,
    Exist = 17,
    CrossDeviceLink = 18,
    NoDev = 19,
    NotDir = 20,
    IsDir = 21,
    InvalidArgument = 22,
    NFile = 23,
    ManyFiles = 24,
    NoTTY = 25,
    TextBusy = 26,
    FileBig = 27,
    NoSpace = 28,
    SeekPipe = 29,
    ReadOnlyFS = 30,
    ManyLinks = 31,
    BrokenPipe = 32,
    MathOutsideDomain = 33,
    MathRange = 34,
    DeadLock = 35,
    NameTooLong = 36,
    NoLock = 37,
    InvalidSyscallNumber = 38,
    NotEmpty = 39,
    Loop = 40,
    NoMessage = 42,
    IdentifierRemoved = 43,
    ChannelRange = 44,
    L2NoSync = 45,
    L3Halted = 46,
    L3Reset = 47,
    LinkOutOfRange = 48,
    UNATCH = 49,
    NoCSI = 50,
    L2Halted = 51,
    BadExchange = 52,
    BadRequestDescriptor = 53,
    ExchangeFull = 54,
    NoAnode = 55,
    BadRequestCode = 56,
    BadSlot = 57,
    BadFont = 59,
    NoStream = 60,
    NoData = 61,
    TimeExpired = 62,
    NoStreamResources = 63,
    NoNetwork = 64,
    NoPackage = 65,
    Remote = 66,
    NoLink = 67,
    Advertise = 68,
    Srmount = 69,
    Comm = 70,
    Proto = 71,
    MultiHop = 72,
    DotDot = 73,
    BadMessage = 74,
    Overflow = 75,
    NotUnique = 76,
    BadFD = 77,
    RemoteChanged = 78,
    LibraryAccess = 79,
    BadLibrary = 80,
    LibrarySection = 81,
    MaxLibrary = 82,
    ExecLibrary = 83,
    IllegalSequence = 84,
    Restart = 85,
    StreamPipe = 86,
    Users = 87,
    NotSocket = 88,
    DestinationAddressRequired = 89,
    MessageSize = 90,
    Prototype = 91,
    NoProtocolOption = 92,
    ProtocolNotSupported = 93,
    SocketTypeNotSupported = 94,
    OperationNotSupported = 95,
    ProtocolFamilyNotSupported = 96,
    AddressFamilyNotSupported = 97,
    AddressInUse = 98,
    AddressNotAvailable = 99,
    NetworkDown = 100,
    NetworkUnrechable = 101,
    NetworkReset = 102,
    ConnectionAborted = 103,
    ConnectionReset = 104,
    NoBufferSpaceAvailable = 105,
    IsConnected = 106,
    NotConnected = 107,
    Shutdown = 108,
    TooManyRefs = 109,
    TimedOut = 110,
    ConnectionRefused = 111,
    HostDown = 112,
    HostUnrechable = 113,
    Already = 114,
    InProgress = 115,
    Stale = 116,
    NeedsCleaning = 117,
    NotXENIXTypeFile = 118,
    NoXENIXSemaphoresAvailable = 119,
    IsName = 120,
    RemoteIO = 121,
    QuotaExceeded = 122,
    NoMedium = 123,
    MediumType = 124,
    Cancelled = 125,
    NoKey = 126,
    KeyExpired = 127,
    KeyRevoked = 128,
    KeyRejected = 129,
    OwnerDead = 130,
    NotRecoverable = 131,
    RFKill = 132,
    HWPoison = 133,
};
consteval u32 operator&(Errno&& code) { return (u32)code; }

// clang-format off
constexpr const c_string error_codes[] {
    [&Errno::NoError] = "No error",
    [&Errno::Permission] = "Operation not permitted",
    [&Errno::NoEntry] = "No such file or directory",
    [&Errno::Search] = "No such process",
    [&Errno::Interrupted] = "Interrupted system call",
    [&Errno::IO] = "I/O error",
    [&Errno::NoIO] = "No such device or address",
    [&Errno::TooBig] = "Argument list too long",
    [&Errno::NoExec] = "Exec format error",
    [&Errno::BadFile] = "Bad file number",
    [&Errno::Child] = "No child processes",
    [&Errno::Again] = "Try again",
    [&Errno::NoMemory] = "Out of memory",
    [&Errno::Access] = "Permission denied",
    [&Errno::Fault] = "Bad address",
    [&Errno::NotBlock] = "Block device required",
    [&Errno::Busy] = "Device or resource busy",
    [&Errno::Exist] = "File exists",
    [&Errno::CrossDeviceLink] = "Cross-device link",
    [&Errno::NoDev] = "No such device",
    [&Errno::NotDir] = "Not a directory",
    [&Errno::IsDir] = "Is a directory",
    [&Errno::InvalidArgument] = "Invalid argument",
    [&Errno::NFile] = "File table overflow",
    [&Errno::ManyFiles] = "Too many open files",
    [&Errno::NoTTY] = "Not a TTY",
    [&Errno::TextBusy] = "Text file busy",
    [&Errno::FileBig] = "File too large",
    [&Errno::NoSpace] = "No space left on device",
    [&Errno::SeekPipe] = "Illegal seek",
    [&Errno::ReadOnlyFS] = "Read-only file system",
    [&Errno::ManyLinks] = "Too many links",
    [&Errno::BrokenPipe] = "Broken pipe",
    [&Errno::MathOutsideDomain] = "Math argument outside domain of function",
    [&Errno::MathRange] = "Math result not representable",
    [&Errno::DeadLock] = "Resource deadlock would occur",
    [&Errno::NameTooLong] = "File name too long",
    [&Errno::NoLock] = "No record locks available",
    [&Errno::InvalidSyscallNumber] = "Invalid system call number",
    [&Errno::NotEmpty] = "Directory not empty",
    [&Errno::Loop] = "Too many symbolic links encountered",
    [&Errno::NoMessage] = "No message of desired type",
    [&Errno::IdentifierRemoved] = "Identifier removed",
    [&Errno::ChannelRange] = "Channel number out of range",
    [&Errno::L2NoSync] = "Level 2 not synchronized",
    [&Errno::L3Halted] = "Level 3 halted",
    [&Errno::L3Reset] = "Level 3 reset",
    [&Errno::LinkOutOfRange] = "Link number out of range",
    [&Errno::UNATCH] = "Protocol driver not attached",
    [&Errno::NoCSI] = "No CSI structure available",
    [&Errno::L2Halted] = "Level 2 halted",
    [&Errno::BadExchange] = "Invalid exchange",
    [&Errno::BadRequestDescriptor] = "Invalid request descriptor",
    [&Errno::ExchangeFull] = "Exchange full",
    [&Errno::NoAnode] = "No anode",
    [&Errno::BadRequestCode] = "Invalid request code",
    [&Errno::BadSlot] = "Invalid slot",
    [&Errno::BadFont] = "Bad font file format",
    [&Errno::NoStream] = "Device not a stream",
    [&Errno::NoData] = "No data available",
    [&Errno::TimeExpired] = "Timer expired",
    [&Errno::NoStreamResources] = "Out of streams resources",
    [&Errno::NoNetwork] = "Machine is not on the network",
    [&Errno::NoPackage] = "Package not installed",
    [&Errno::Remote] = "Object is remote",
    [&Errno::NoLink] = "Link has been severed",
    [&Errno::Advertise] = "Advertise error",
    [&Errno::Srmount] = "Srmount error",
    [&Errno::Comm] = "Communication error on send",
    [&Errno::Proto] = "Protocol error",
    [&Errno::MultiHop] = "Multihop attempted",
    [&Errno::DotDot] = "RFS specific error",
    [&Errno::BadMessage] = "Not a data message",
    [&Errno::Overflow] = "Value too large for defined data type",
    [&Errno::NotUnique] = "Name not unique on network",
    [&Errno::BadFD] = "File descriptor in bad state",
    [&Errno::RemoteChanged] = "Remote address changed",
    [&Errno::LibraryAccess] = "Can not access a needed shared library",
    [&Errno::BadLibrary] = "Accessing a corrupted shared library",
    [&Errno::LibrarySection] = ".lib section in a.out corrupted",
    [&Errno::MaxLibrary] = "Attempting to link in too many shared libraries",
    [&Errno::ExecLibrary] = "Cannot exec a shared library directly",
    [&Errno::IllegalSequence] = "Illegal byte sequence",
    [&Errno::Restart] = "Interrupted system call should be restarted",
    [&Errno::StreamPipe] = "Streams pipe error",
    [&Errno::Users] = "Too many users",
    [&Errno::NotSocket] = "Socket operation on non-socket",
    [&Errno::DestinationAddressRequired] = "Destination address required",
    [&Errno::MessageSize] = "Message too long",
    [&Errno::Prototype] = "Protocol wrong type for socket",
    [&Errno::NoProtocolOption] = "Protocol not available",
    [&Errno::ProtocolNotSupported] = "Protocol not supported",
    [&Errno::SocketTypeNotSupported] = "Socket type not supported",
    [&Errno::OperationNotSupported] = "Operation not supported on transport endpoint",
    [&Errno::ProtocolFamilyNotSupported] = "Protocol family not supported",
    [&Errno::AddressFamilyNotSupported] = "Address family not supported by protocol",
    [&Errno::AddressInUse] = "Address already in use",
    [&Errno::AddressNotAvailable] = "Cannot assign requested address",
    [&Errno::NetworkDown] = "Network is down",
    [&Errno::NetworkUnrechable] = "Network is unreachable",
    [&Errno::NetworkReset] = "Network dropped connection because of reset",
    [&Errno::ConnectionAborted] = "Software caused connection abort",
    [&Errno::ConnectionReset] = "Connection reset by peer",
    [&Errno::NoBufferSpaceAvailable] = "No buffer space available",
    [&Errno::IsConnected] = "Transport endpoint is already connected",
    [&Errno::NotConnected] = "Transport endpoint is not connected",
    [&Errno::Shutdown] = "Cannot send after transport endpoint shutdown",
    [&Errno::TooManyRefs] = "Too many references: cannot splice",
    [&Errno::TimedOut] = "Connection timed out",
    [&Errno::ConnectionRefused] = "Connection refused",
    [&Errno::HostDown] = "Host is down",
    [&Errno::HostUnrechable] = "No route to host",
    [&Errno::Already] = "Operation already in progress",
    [&Errno::InProgress] = "Operation now in progress",
    [&Errno::Stale] = "Stale file handle",
    [&Errno::NeedsCleaning] = "Structure needs cleaning",
    [&Errno::NotXENIXTypeFile] = "Not a XENIX named type file",
    [&Errno::NoXENIXSemaphoresAvailable] = "No XENIX semaphores available",
    [&Errno::IsName] = "Is a named type file",
    [&Errno::RemoteIO] = "Remote I/O error",
    [&Errno::QuotaExceeded] = "Quota exceeded",
    [&Errno::NoMedium] = "No medium found",
    [&Errno::MediumType] = "Wrong medium type",
    [&Errno::Cancelled] = "Operation Canceled",
    [&Errno::NoKey] = "Required key not available",
    [&Errno::KeyExpired] = "Key has expired",
    [&Errno::KeyRevoked] = "Key has been revoked",
    [&Errno::KeyRejected] = "Key was rejected by service",
    [&Errno::OwnerDead] = "Owner died",
    [&Errno::NotRecoverable] = "State not recoverable",
    [&Errno::RFKill] = "Operation not possible due to RF-kill",
    [&Errno::HWPoison] = "Memory page has hardware error",
};
// clang-format on
constexpr const i32 error_codes_size
    = sizeof(error_codes) / sizeof(error_codes[0]);
#else
#    warning "unimplemented"
#endif

}

c_string Error::errno_to_string(int code)
{
#if __linux__
    if (code < error_codes_size && error_codes[code])
        return error_codes[code];
    auto buffer = MUST(StringBuffer::create_saturated_fill(
        "sloppy coding ("sv, code, ")\0"sv));
    return buffer.leak();
#else
#    warning "unimplemented"
    return strerror(code);
#endif
}

ErrorCodes Error::s_error_codes;

}
